### ISSUE TITLE
Error thrown at Homebridge startup

### ISSUE THREAD

**Issue by lpettinati** [tagyoureit/homebridge-luxor#1]
I updated to the latest version and am seeing the following error thrown during startup. Incidentally, I'm not seeing additional switches getting created for themes, which makes sense given the error being thrown.

[9/23/2017, 8:05:16 PM] Error in didFinishLaunching TypeError: controller.ThemeListGet is not a function
    at LuxorPlatform.getControllerThemeList (/usr/lib/node_modules/homebridge-luxor/index.js:139:21)
    at /usr/lib/node_modules/homebridge-luxor/index.js:403:19
    at tryCatcher (/usr/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by tagyoureit** [comment]
I'm guessing that you have a ZD controller?  I only tested this with ZDC, but... I just pushed up some code so it should work on ZD as well.  Try it out, and I'll try to also find some time to test with my ZD module but it should load for you (if that was the problem).

**Comment by lpettinati** [comment]
Thanks — I do have a ZD controller (not ZDC).

I wasn't sure how to update from the master branch so I copied the changed files manually. On the good side, no more error at load time and the two switches were added and worked as described.

Now... I don't know if this is because I manually moved specific files over, but the Home app showed all pre-existing lights as "Not Responding". I could still turn them on/off and see that they were on/off and could verify in the Homebridge log that things were working. Reverted back to a fresh install of v2.0.1, deleted accessory and persist directories, removed Homebridge hub from Homekit and reinstalled. All's back to normal now. Will wait for the code to be pushed out before trying again.

**Comment by tagyoureit** [comment]
You should just need to run `npm update homebridge-luxor` to get the latest.  Try again... I just made some changes and pushed up the code.  Let me know if the status is updating for you.  It is working for me.

**Comment by lpettinati** [comment]
The command npm update homebridge-luxor is pulling from the published
module and not the branch in GitHub. I manually downloaded the new files
and it's all working now.

One thing... looks like package.json still references version 2.0.1.

Thank you!!!

**Comment by tagyoureit** [comment]
Thanks, just bumped the version.  Glad to hear it is working!  Let me know if you have any other feedback.  Closing this for now.
