### ISSUE TITLE
execution error in 4.2.6

### ISSUE THREAD

**Issue by garyhooper** [tagyoureit/homebridge-luxor#24]
Can no longer connect using the latest 4.2.6:

```
Luxor was not able to connect to connect to the controller.  TypeError: axios is not a function
    at LuxorPlatform.getControllerAsync (/homebridge/node_modules/homebridge-luxor/src/LuxorPlatform.ts:61:36)
    at LuxorPlatform.didFinishLaunchingAsync (/homebridge/node_modules/homebridge-luxor/src/LuxorPlatform.ts:254:31)
```

**Comment by tagyoureit** [comment]
I accepted a PR and seems Axios had a lot of [issues](https://github.com/axios/axios/issues/5038)... reverted back to 0.27.2.  Try now.

**Comment by garyhooper** [comment]
Solved it.  Thanks!

**Comment by tagyoureit** [comment]
And just for clarity, the PR didn't include the updated deps, I did that... didn't want to point fingers at anyone else. ;)
