### ISSUE TITLE
Connection Error on Set Color

### ISSUE THREAD

**Issue by adamgross** [tagyoureit/homebridge-luxor#6]
Got everything up and running (oddly after a different connect error that disappeared on its own), and am getting a connection error when attempting to change the Group color via the Home app.
```
[2019-8-27 10:42:14] [Luxor] ZDC Accessory Test five calling colorListSet (from setHue) with value hue:28
[2019-8-27 10:42:14] [Luxor] ZDC Accessory Test five calling colorListSet (from setSaturation) with value:23
[2019-8-27 10:42:14] [Luxor] Error trying to set the color: Error: RequestError: Error: connect ECONNREFUSED 192.168.86.23:80 
Error: connect ECONNREFUSED 192.168.86.23:80
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_TWO_Controller.js:215:19
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
[2019-8-27 10:42:14] [Luxor] Error trying to set the color: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:326:21
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
Unhandled rejection Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:250:13
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

[2019-8-27 10:42:14] [Luxor] ZDC Accessory Test five calling colorListSet (from setSaturation) with value:100
[2019-8-27 10:42:14] [Luxor] ZDC Accessory Test five calling colorListSet (from setHue) with value hue:30
[2019-8-27 10:42:14] [Luxor] ZDC Accessory Test five calling colorListSet (from setHue) with value hue:30
[2019-8-27 10:42:14] [Luxor] ZDC Accessory Test five calling colorListSet (from setSaturation) with value:100
[2019-8-27 10:42:14] [Luxor] ZDC Accessory Test five calling colorListSet (from setHue) with value hue:0
[2019-8-27 10:42:14] [Luxor] ZDC Accessory Test five calling colorListSet (from setSaturation) with value:0
Unhandled rejection Error: RequestError: Error: connect ECONNREFUSED 192.168.86.23:80 
Error: connect ECONNREFUSED 192.168.86.23:80
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_TWO_Controller.js:305:19
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)


```

**Comment by adamgross** [comment]
Yes - everything works except changing color.  I’m using the iOS Home
native app

**Comment by tagyoureit** [comment]
Can you try pulling the code from the [LXTWO](https://github.com/tagyoureit/homebridge-luxor/tree/LXTWO) branch?  I was making some changes there for that controller.

**Comment by adamgross** [comment]
Thats the branch I'm on (and started with) thanks

**Comment by tagyoureit** [comment]
Hi, can you try pulling the latest code and trying again?  I changed a few things on the LXTWO controller (although I wasn't able to test out the color list functionality due to a lack of color lights).  Hopeful the changes I made will alleviate these issues.

**Comment by adamgross** [comment]
Unfortunately I'm still getting an error --

`[2020-1-30 16:47:39] [Luxor] ZDC Accessory Front Path One color assignment was changed outside of HomeKit.  Changing to 245
[2020-1-30 16:47:39] [Luxor] Error trying to set the color: TypeError: callback_h is not a function
    at /Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/ZDC_Light.js:326:21
    at tryCatcher (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
Unhandled rejection Error: This callback function has already been called by someone else; it can only be called one time.
    at /Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/ZDC_Light.js:291:13
    at tryCatcher (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/adam/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)

[2020-1-30 16:47:39] [Luxor] was not able to run GroupListEdit: RequestError: Error: connect ECONNREFUSED 192.168.86.23:80
`

**Comment by adamgross** [comment]
Update -- I did a full re-install (the key seemed to be deleting the cache), and it appears to working now -- thanks!

**Comment by adamgross** [comment]
One more update -- I was still getting occasional connection refused errors on GetTheme and GetGroup

`[2/7/2020, 4:08:42 PM] [Luxor] was not able to run GroupListEdit: RequestError: Error: connect ECONNREFUSED 192.168.86.23:80`

I increased the timeout value on those requests from 5000 to 50000 and it seemed to help -- hopefully that will hold up

```
    timeoutGroupList = setTimeout(() => {
            timeoutGroupList = null;
        }, 50000)

```

**Comment by tagyoureit** [comment]
Hi, glad to hear that it worked.  I was about to start tracking down this error again and saw your last two comments.  

FYI, the timeout that you increased acts as a rate limiter.  Instead of rechecking for controller changes after 5 seconds it will now do it after 50s.  This really shouldn't decrease the number of errors that are happening but maybe the frequency.  If these are intermittent, you might want to check out something like Wireshark to snoop on the http transmissions.  

In the picture below (in WireShark), you can see the TCP packets setting up the transmission and then the two HTTP calls (`POST /GroupListGet.json...`) and (`HTTP/1.1 200 OK...`) with the correct response.  The whole thing should take a matter of milliseconds to complete.  If you aren't seeing a timely response then you might want to check your networking to make sure you aren't having intermittent issues there.  Or you might see something further there about why the connection is refused.

![2020-02-07_22-24-01](https://user-images.githubusercontent.com/1646840/74080443-123ea080-49f9-11ea-941c-75a813262193.jpeg)

I'll close out this issue but feel free to re-open if you have more issues with the above.  Or open a new issue for the ECONNREFUSED or anything else.
