### ISSUE TITLE
Error - TypeError: controller.ColorListGet is not a function

### ISSUE THREAD

**Issue by FrothyDog** [tagyoureit/homebridge-luxor#7]
I have a ZD controller. For some reason I am getting an error as follows. It seems to be trying to get color from my non-color capable controller.

[5/9/2020, 16:17:00] TypeError: controller.ColorListGet is not a function
    at ZDC_Light.getHueSaturation (/usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:260:23)
    at Characteristic.emit (events.js:310:20)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:451:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1219:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1147:10)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:900:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:307:24)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[5/9/2020, 16:17:00] Got SIGTERM, shutting down Homebridge...

**Comment by FrothyDog** [comment]
I am not seeing the above issue any longer, but am still getting a lot of errors with this plugin. Here is the latest log I have from today -

[5/11/2020, 17:18:01] [Luxor] was not able to retrieve light groups from controller. RequestError: Error: connect ETIMEDOUT 192.168.100.19:80
    at new RequestError (/usr/local/lib/node_modules/homebridge-luxor/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-luxor/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-luxor/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-luxor/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  cause: Error: connect ETIMEDOUT 192.168.100.19:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
   {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.100.19',
    port: 80
  },
  error: Error: connect ETIMEDOUT 192.168.100.19:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
   {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '192.168.100.19',
    port: 80
  },
  options: {
    url: 'http://192.168.100.19/GroupListGet.json',
    method: 'POST',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
[5/11/2020, 17:18:01] [Luxor] Back Kitchen: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Back Pergola: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Back Lemon: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Back Lagerstroemia: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Back Bamboo: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Back Step Lights: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Front Podocarpus: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Front Maple: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Front Pathway : Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Front Birch: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Back Kitchen: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Back Pergola: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Back Lemon: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Back Lagerstroemia: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] Back Bamboo: Not able to connect to the controller.  Error: TypeError: Cannot read property 'GroupList' of undefined
[5/11/2020, 17:18:01] [Luxor] ZD Accessory Front Pathway : Error Updating Brightness ReferenceError: log is not defined
    at /usr/local/lib/node_modules/homebridge-luxor/ZD_Light.js:192:13
    at /usr/local/lib/node_modules/homebridge-luxor/ZD_Light.js:254:13
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

[5/11/2020, 17:18:01] [Luxor] ZD Accessory Front Birch: Error Updating Brightness ReferenceError: log is not defined
    at /usr/local/lib/node_modules/homebridge-luxor/ZD_Light.js:192:13
    at /usr/local/lib/node_modules/homebridge-luxor/ZD_Light.js:254:13
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

**Comment by FrothyDog** [comment]
I have rebooted a few times now. It gets these errors every time I start up. 
Again - I see "ZDC" accessories listed when I have a ZD controller.

[5/14/2020, 11:04:42] [Luxor] ZDC Accessory Front Birch: initializing cached ZDC light Front Birch
[5/14/2020, 11:04:42] [Luxor] ZDC Accessory Front Pathway : initializing cached ZDC light Front Pathway 
[5/14/2020, 11:04:42] [Luxor] ZDC Accessory Front Maple: initializing cached ZDC light Front Maple
[5/14/2020, 11:04:42] [Luxor] ZDC Accessory Front Podocarpus: initializing cached ZDC light Front Podocarpus
[5/14/2020, 11:04:42] [Luxor] ZDC Accessory Back Step Lights: initializing cached ZDC light Back Step Lights
[5/14/2020, 11:04:42] [Luxor] ZDC Accessory Back Bamboo: initializing cached ZDC light Back Bamboo
[5/14/2020, 11:04:42] [Luxor] ZDC Accessory Back Lagerstroemia: initializing cached ZDC light Back Lagerstroemia
[5/14/2020, 11:04:42] [Luxor] ZDC Accessory Back Lemon: initializing cached ZDC light Back Lemon
[5/14/2020, 11:04:42] [Luxor] ZDC Accessory Back Pergola: initializing cached ZDC light Back Pergola
[5/14/2020, 11:04:42] [Luxor] ZDC Accessory Back Kitchen: initializing cached ZDC light Back Kitchen
[5/14/2020, 11:04:42] [Luxor] Luxor Theme Night Lights: initializing cached Luxor Theme Night Lights
[5/14/2020, 11:04:42] [Luxor] Luxor Theme Illuminate all lights: initializing cached Luxor Theme Illuminate all lights
[5/14/2020, 11:04:42] [Luxor] Luxor Theme Extinguish all lights: initializing cached Luxor Theme Extinguish all lights
Unhandled rejection TypeError: controller.ColorListGet is not a function
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:147:35
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

Unhandled rejection TypeError: controller.ColorListGet is not a function
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:147:35
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

Unhandled rejection TypeError: controller.ColorListGet is not a function
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:147:35
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

Unhandled rejection TypeError: controller.ColorListGet is not a function
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:147:35
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

Unhandled rejection TypeError: controller.ColorListGet is not a function
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:147:35
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

Unhandled rejection TypeError: controller.ColorListGet is not a function
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:147:35
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

Unhandled rejection TypeError: controller.ColorListGet is not a function
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:147:35
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

Unhandled rejection TypeError: controller.ColorListGet is not a function
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:147:35
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

Unhandled rejection TypeError: controller.ColorListGet is not a function
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:147:35
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

Unhandled rejection TypeError: controller.ColorListGet is not a function
    at /usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:147:35
    at tryCatcher (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-luxor/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

[5/14/2020, 11:04:42] [Luxor] Found 10 light groups.
[5/14/2020, 11:04:42] [Luxor] Found 1 themes.
[5/14/2020, 11:04:42] [Luxor] Finished initializing

**Comment by FrothyDog** [comment]
If I try to query my lights in the Home app this plugin is crashing and causing Homebridge to restart - 

[5/14/2020, 11:07:58] [Harmony Hub] (Harmony Hub)INFO - Discovered Activity : Nintendo Switch
[5/14/2020, 11:08:39] TypeError: controller.ColorListGet is not a function
    at ZDC_Light.getHueSaturation (/usr/local/lib/node_modules/homebridge-luxor/ZDC_Light.js:260:23)
    at Characteristic.emit (events.js:310:20)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:183:23)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:755:32
    at Array.forEach (<anonymous>:null:null)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:696:18)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:797:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by FrothyDog** [comment]
I have reverted back to version 2.0.2 and this is working flawlessly for me.

**Comment by munskey** [comment]
I'm on 3.0.2, as well, with a ZD (non-color) controller and have the exact same issue, log output and homebridge crash.

The lack of dev updates suggest this plugin may be abandoned, I'll try installing 2.0.2, thanks for the tip @FrothyDog

**Comment by FrothyDog** [comment]
Unfortunately I think you're correct. It would be great to get an update to fix this issue but the dev. seems to have moved on. Hopefully someone else can resurrect it one of these days.

**Comment by tagyoureit** [comment]
I re-wrote the plug-in.  It's now fully compatible with Homebridge and Homebridge UI (tested on 1.3.0 and later).  Please give it a try.
